#!/bin/bash

# Default Configurations
readonly DEFAULT_SUMMARY_FILE="testSummary.md"
readonly DEFAULT_PORT=22200
readonly DEFAULT_PASSWORD="Alilepro135!"
readonly DEFAULT_SERVER_BINARY="./bin/irc-server"
readonly DEFAULT_TIMEOUT=5
readonly DEFAULT_LOG_FILE="irc_test.log"
readonly DEFAULT_MAX_PARALLEL_TESTS=5

# Runtime Configuration
SUMMARY_FILE=$DEFAULT_SUMMARY_FILE
PORT=$DEFAULT_PORT
PASSWORD=$DEFAULT_PASSWORD
SERVER_BINARY=$DEFAULT_SERVER_BINARY
TIMEOUT=$DEFAULT_TIMEOUT
LOG_FILE=$DEFAULT_LOG_FILE
MAX_PARALLEL_TESTS=$DEFAULT_MAX_PARALLEL_TESTS

# Test Counters
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
SKIPPED_TESTS=0
TEST_START_TIME=""
TEST_END_TIME=""

# State Flags
DEBUG=0
VERBOSE=0
QUIET=0
NO_COLOR=0
SKIP_CLEANUP=0
CUSTOM_TESTS=""

# Array to store failed tests
declare -a FAILED_TESTS_ARRAY
